<?php

/**
 * Implements hook_permission().
 */
function merchant_permission() {
  return array(
    'administer merchant' => array(
      'title' => t('Administer merchant module'),
    ),
  );
}



/**
 * Implements hook_menu().
 */
function merchant_menu() {

  $items = [];

  $items['admin/merchant'] = [
    'title' => t('Merchant'),
    'description' => t('display all merchant list.'),
    'page callback' => 'merchant_list',
    'access arguments' => ['administer merchant'],
    'file' => 'merchant.admin.inc',
  ];

  $items['merchant'] = [
    'title' => t('Merchant'),
    'description' => t('display all merchant list.'),
    'page callback' => 'merchant_list_page',
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'file' => 'merchant.pages.inc',
  ];

  return $items;
}


/**
 * Implements hook_block_info().
 */

function merchant_block_info() {
  $blocks['merchant_list_filter'] = [
    'info' => t('Merchant list filter search')
  ];

  return $blocks;
}


/**
 * Implements hook_block_view().
 */

function merchant_block_view($delta = '') {
  $block = [];
  
  switch ($delta) {
    case 'merchant_list_filter':
      $block['subject'] = t('Search merchant');
      $block['content'] = drupal_get_form('merchant_list_filter_form');
      break;
  }

  return $block;
}
