<?php

/**
 * Implements hook_permission().
 */
function merchant_permission() {
  return array(
    'administer merchant' => [
      'title' => 'مدیریت پذیرندگان',
    ],
  );
}



/**
 * Implements hook_menu().
 */
function merchant_menu() {

  $items = [];

  $items['admin/merchant'] = [
    'title' => 'پذیرندگان',
    'description' => 'نمایش لیست تمامی پذیرندگان',
    'page callback' => 'merchant_list',
    'access arguments' => ['administer merchant'],
    'file' => 'merchant.admin.inc',
  ];
  
  $items['admin/merchant/add'] = [
    'title' => 'افزودن پذیرنده',
    'description' => 'افزودن یک پذیرنده',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['merchant_add_form'],
    'access arguments' => ['administer merchant'],
    'file' => 'merchant.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  ];
  
  $items['admin/merchant/edit/%'] = [
    'title' => 'ویرایش پذیرنده',
    'description' => 'ویرایش یک پذیرنده',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['merchant_add_form', 3],
    'access arguments' => ['administer merchant'],
    'file' => 'merchant.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  ];

  $items['merchant'] = [
    'title' => 'پذیرندگان',
    'description' => 'نمایش لیست تمامی پذیرندگان',
    'page callback' => 'merchant_list_page',
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'file' => 'merchant.pages.inc',
  ];

  return $items;
}


/**
 * Implements hook_block_info().
 */

function merchant_block_info() {
  $blocks['merchant_list_filter'] = [
    'info' => 'جستجوی پذیرندگان'
  ];

  return $blocks;
}


/**
 * Implements hook_block_view().
 */

function merchant_block_view($delta = '') {
  $block = [];
  
  switch ($delta) {
    case 'merchant_list_filter':
      $block['subject'] = 'جستجوی پذیرندگان';
      $block['content'] = drupal_get_form('merchant_list_filter_form');
      break;
  }

  return $block;
}
