<?php

/**
 * 
 * Implements hook_theme()
 */
function jssor_slider_theme() {
  return [
    'banner_slider' => [
      'variables' => ['images' => []],
      'template' => 'templates/banner_slider'
    ],
    'thumbnail_navigator_with_arrows' => [
      'variables' => ['images' => []],
      'template' => 'templates/thumbnail_navigator_with_arrows'
    ]
  ];
}


/**
 * Implements hook_block_info()
 */
function jssor_slider_block_info() {
  $blocks['main_slider'] = [
    'info' => 'اسلایدر صفحه اصلی'
  ];

  return $blocks;
}



/**
 * Implements hook_block_view()
 */
function jssor_slider_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'main_slider':
      $images = [];
      $all_node = taxonomy_select_nodes(1, false);
      foreach ($all_node as $node) {
        $node = node_load($node);
        $images[] = [
          'uri' => $node->field_image['und'][0]['uri'],
          'thumb' => $node->title
        ];
      }
      $block['content'] = theme('banner_slider', ['images' => $images]);
      break;
  }

  return $block;
}