<?php

/**
 * Implements hook_permission()
 */
function contact_us_permission() {
  return array(
    'administer contact_us' => [
      'title' => 'مشخصات تماس',
    ],
  );
}



/**
 * Implements hook_menu()
 */
function contact_us_menu() {
  
  $items = [];
  
  $items['contact-us'] = [
    'title' => 'ارتباط با ما',
    'page callback' => 'contact_us_page_callback',
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'file' => 'contact_us.pages.inc',
  ];
  
  $items['admin/contact-us-setting'] = [
    'title' => 'مشخصات تماس',
    'description' => 'مدیریت مشخصات تماس در صفحه ارتباط با ما',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['contact_us_info_admin_form'],
    'access arguments' => ['administer contact_us'],
    'file' => 'contact_us.admin.inc',
  ];
  
  return $items;  
}



function contact_us_page_callback() {
  
  $page_output['contact_us_form'] = [
    drupal_get_form('contact_us_page_form')
  ];
  
  $phone = variable_get('contact_us_phone', ' 09134311348');
  $fax = variable_get('contact_us_fax', '09162392091');
  $email = variable_get('contact_us_email', 'eliyaomid@gmail.com');
  $address = variable_get('contact_us_address', 'isfahan, iran');
  
  drupal_add_js('http://maps.googleapis.com/maps/api/js?key=AIzaSyBIOCfIlB3NTW2pPx4T7dajJ9HZV57_BCM', ['type'=>'external']);
  drupal_add_js(drupal_get_path('module', 'contact_us').'/js/googlemap.js', ['type'=>'file']);
  $contact_us_info_markup = <<<EOT
  <div class="panel panel-default">
    <div class="panel-heading">مشخصات تماس</div>
    <ul class="list-group">
      <li class="list-group-item"><strong>تلفن:</strong> $phone</li>
      <li class="list-group-item"><strong>فکس:</strong> $fax</li>
      <li class="list-group-item"><strong>ایمیل:</strong> $email</li>
      <li class="list-group-item"><strong>آدرس:</strong> $address</li>
      <li class="list-group-item"><div id="googleMap" class="form-control" style="height: 200px; width: 100%;"></div></li>
    </ul>
  </div>
EOT;
  $page_output['contact_us_info'] = [
    '#type' => 'markup',
    '#markup' => $contact_us_info_markup,
    '#prefix' => '<div class="col-sm-7">',
    '#suffix' => '</div>',
  ];

  return $page_output;
}



/**
 * Implements hook_mail()
 */
function contact_us_mail($key, &$message, $params) {
  $language = $message['language'];
  $variables = array(
    '!site-name' => variable_get('site_name', 'Drupal'),
    '!subject' => $params['subject'],
    '!category' => isset($params['category']['category']) ? $params['category']['category'] : '',
    '!form-url' => url($_GET['q'], array('absolute' => TRUE, 'language' => $language)),
    '!sender-name' => format_username($params['sender']),
    '!sender-url' => $params['sender']->uid ? url('user/' . $params['sender']->uid, array('absolute' => TRUE, 'language' => $language)) : $params['sender']->mail,
  );

  switch ($key) {
    case 'page_mail':
    case 'page_copy':
      $message['subject'] .= t('[!category] !subject', $variables, array('langcode' => $language->language));
      $message['body'][] = t("!sender-name (!sender-url) sent a message using the contact form at !form-url.", $variables, array('langcode' => $language->language));
      $message['body'][] = $params['message'];
      break;
  }
}